/**
 * ============================================================
 * VERIFY EMAIL SCREEN
 * ============================================================
 * Step 2 of the auth flow. Shows six boxes for a 6-digit code
 * sent by email (NOT a magic link — see docs/SUPABASE_SETUP.md
 * for the one-time dashboard change required: the "Confirm signup"
 * email template must use {{ .Token }} instead of
 * {{ .ConfirmationURL }} for this to work).
 *
 * On successful verification we DON'T navigate straight to the
 * dashboard — we go to WaitingApproval, because a verified email
 * only proves the person owns that inbox, not that the Chairman
 * has vetted them as a real chama member yet.
 * ============================================================
 */
import React, { useEffect, useRef, useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Alert,
} from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { supabase } from '../../lib/supabase';
import { colors, spacing, radius } from '../../lib/theme';
import type { AuthStackParamList } from '../../navigation/AuthNavigator';

type Props = NativeStackScreenProps<AuthStackParamList, 'VerifyEmail'>;

const CODE_LENGTH = 6;
const RESEND_COOLDOWN_SECONDS = 60;

export default function VerifyEmailScreen({ route, navigation }: Props) {
  const { email } = route.params;

  // One string per digit box, e.g. ["4","8","2","9","1","5"].
  const [digits, setDigits] = useState<string[]>(Array(CODE_LENGTH).fill(''));
  const [loading, setLoading] = useState(false);
  const [resending, setResending] = useState(false);
  const [resendCooldown, setResendCooldown] = useState(RESEND_COOLDOWN_SECONDS);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  // Refs so we can auto-advance focus from box to box as the
  // member types, and jump back on backspace.
  const inputRefs = useRef<Array<TextInput | null>>([]);

  useEffect(() => {
    if (resendCooldown <= 0) return;
    const timer = setInterval(() => setResendCooldown((s) => s - 1), 1000);
    return () => clearInterval(timer);
  }, [resendCooldown]);

  function handleDigitChange(text: string, index: number) {
    setErrorMessage('');
    setSuccessMessage('');
    // Only accept a single digit; anything else (paste of full
    // code, letters, etc.) is ignored at this box but see the
    // paste-friendly branch below for the common case of a user
    // pasting the whole 6-digit code into the first box.
    const clean = text.replace(/\D/g, '');

    if (clean.length > 1) {
      // Handles pasting the full code at once.
      const pasted = clean.slice(0, CODE_LENGTH).split('');
      const next = [...digits];
      pasted.forEach((d, i) => {
        if (index + i < CODE_LENGTH) next[index + i] = d;
      });
      setDigits(next);
      const lastFilled = Math.min(index + pasted.length, CODE_LENGTH - 1);
      inputRefs.current[lastFilled]?.focus();
      return;
    }

    const next = [...digits];
    next[index] = clean;
    setDigits(next);

    if (clean && index < CODE_LENGTH - 1) {
      inputRefs.current[index + 1]?.focus();
    }
  }

  function handleKeyPress(e: any, index: number) {
    // Backspace on an empty box moves focus to the previous box,
    // matching the standard OTP-input UX pattern.
    if (e.nativeEvent.key === 'Backspace' && !digits[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  }

  async function handleVerify() {
    const code = digits.join('');
    if (code.length !== CODE_LENGTH) {
      Alert.alert('Incomplete code', 'Please enter all 6 digits.');
      return;
    }

    setLoading(true);
    try {
      // type: 'signup' because this OTP was generated by
      // auth.signUp() in RegisterScreen. Supabase also supports
      // 'email' / 'recovery' types for other OTP flows.
      const { error } = await supabase.auth.verifyOtp({
        email,
        token: code,
        type: 'signup',
      });

      if (error) throw error;

      // Move the member's profile from PENDING_EMAIL to
      // PENDING_APPROVAL now that their email is confirmed.
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (user) {
        const { error: updateError } = await supabase.rpc('complete_email_verification');
        if (updateError) throw updateError;
      }

      // Pending members must not retain a session that could be mistaken
      // for ACTIVE by another part of the app while awaiting approval.
      await supabase.auth.signOut();
      navigation.replace('WaitingApproval');
    } catch (err: any) {
      setErrorMessage(err.message ?? 'Invalid or expired code.');
      Alert.alert('Verification failed', err.message ?? 'Invalid or expired code.');
    } finally {
      setLoading(false);
    }
  }

  async function handleResend() {
    if (resendCooldown > 0 || resending) return;
    setResending(true);
    setErrorMessage('');
    setSuccessMessage('');
    try {
      const { error } = await supabase.auth.resend({ type: 'signup', email });
      if (error) throw error;
      setResendCooldown(RESEND_COOLDOWN_SECONDS);
      setDigits(Array(CODE_LENGTH).fill(''));
      setSuccessMessage('A new 6-digit code was sent. Check your Gmail inbox and spam folder.');
      inputRefs.current[0]?.focus();
    } catch (err: any) {
      const providerMessage = err.message ?? 'Please try again shortly.';
      const normalizedMessage = providerMessage.toLowerCase();
      const isRateLimited =
        err.status === 429 ||
        normalizedMessage.includes('rate limit') ||
        normalizedMessage.includes('too many') ||
        normalizedMessage.includes('once every');
      const visibleMessage = isRateLimited
        ? 'Supabase has temporarily limited verification emails. Wait for the countdown, then try again. Also check Gmail spam and Promotions.'
        : providerMessage;

      if (isRateLimited) setResendCooldown(RESEND_COOLDOWN_SECONDS);
      setErrorMessage(visibleMessage);
      Alert.alert('Could not resend code', visibleMessage);
    } finally {
      setResending(false);
    }
  }

  return (
    <View style={styles.screen}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Thika Road Chama Group{'\n'}Verify Email</Text>
      </View>

      <View style={styles.content}>
        <Text style={styles.title}>Verify Email</Text>
        <Text style={styles.subtitle}>We sent a 6-digit code to {email}</Text>

        <View style={styles.digitsRow}>
          {digits.map((digit, index) => (
            <TextInput
              key={index}
              ref={(el) => {
                inputRefs.current[index] = el;
              }}
              style={[styles.digitBox, digit ? styles.digitBoxFilled : null]}
              value={digit}
              onChangeText={(text) => handleDigitChange(text, index)}
              onKeyPress={(e) => handleKeyPress(e, index)}
              keyboardType="number-pad"
              maxLength={CODE_LENGTH} // allows the paste-whole-code branch above
              textAlign="center"
            />
          ))}
        </View>

        {errorMessage ? <Text style={styles.errorText}>{errorMessage}</Text> : null}
        {successMessage ? <Text style={styles.successText}>{successMessage}</Text> : null}

        <View style={styles.timerRow}>
          <Text style={styles.timerText}>
            {resendCooldown > 0
              ? `Resend available in ${String(Math.floor(resendCooldown / 60)).padStart(2, '0')}:${String(
                  resendCooldown % 60
                ).padStart(2, '0')}`
              : 'You can request a new code'}
          </Text>
          <TouchableOpacity onPress={handleResend} disabled={resendCooldown > 0 || resending}>
            <Text style={[styles.resendText, resendCooldown > 0 && styles.resendDisabled]}>
              {resending ? 'Sending...' : 'Resend code'}
            </Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity
          style={[styles.button, loading && styles.buttonDisabled]}
          onPress={handleVerify}
          disabled={loading}
        >
          {loading ? <ActivityIndicator color={colors.white} /> : <Text style={styles.buttonText}>Verify</Text>}
        </TouchableOpacity>

        <Text style={styles.helpText}>Didn't receive the code? Check your spam folder</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.white },
  header: {
    backgroundColor: colors.primary,
    paddingTop: 60,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
    borderBottomLeftRadius: radius.lg,
    borderBottomRightRadius: radius.lg,
  },
  headerTitle: { color: colors.white, fontSize: 18, fontWeight: '700' },
  content: { padding: spacing.lg, alignItems: 'center' },
  title: { fontSize: 24, fontWeight: '800', color: colors.text, marginTop: spacing.lg },
  subtitle: { color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.lg, textAlign: 'center' },
  digitsRow: { flexDirection: 'row', gap: 8, marginBottom: spacing.lg },
  digitBox: {
    width: 44,
    height: 56,
    borderWidth: 2,
    borderColor: colors.primaryLight,
    borderRadius: radius.sm,
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
    backgroundColor: colors.primaryLight,
  },
  digitBoxFilled: { borderColor: colors.primary },
  timerRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginBottom: spacing.lg },
  timerText: { color: colors.textMuted },
  resendText: { color: colors.primary, fontWeight: '700' },
  resendDisabled: { color: colors.textMuted },
  button: {
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 16,
    alignItems: 'center',
    width: '100%',
  },
  buttonDisabled: { opacity: 0.6 },
  buttonText: { color: colors.white, fontWeight: '700', fontSize: 16 },
  helpText: { color: colors.textMuted, marginTop: spacing.md, fontSize: 12 },
  errorText: { color: colors.danger, textAlign: 'center', marginBottom: spacing.md },
  successText: { color: colors.success, textAlign: 'center', marginBottom: spacing.md },
});
